### PR TITLE
Add a CIDR option

### PR DESCRIPTION
**Pull request by rasta-mouse**
This PR adds a new IP address CIDR option to the C# version.

### Examples
- `-i 192.168.1.0/24`
- `--cidr 192.168.1.0/24`

Requires tweaking to combine URLs already obtained from the favourites option.

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Awesome, this looks solid. Thanks for taking the time to add this in and send it over

**Comment by rasta-mouse** [comment]
@ChrisTruncer looks like I forgot to change the target framework for the nuget package back from 48 to 45.
https://github.com/FortyNorthSecurity/EyeWitness/blob/master/CS/EyeWitness/packages.config#L6

I think it's breaking your build pipeline?

**Comment by ChrisTruncer** [comment]
Ah, yeah, able to push that update? I'm away from computer right now.

**Comment by ChrisTruncer** [comment]
Hm, I might have to revert this, I'm having issues getting this fixed on my end, just want to give a heads up

**Comment by rasta-mouse** [comment]
No worries.  I couldn't look into it much more because your build pipeline results are not public.

**Comment by ChrisTruncer** [comment]
Looks like right now the error is:

that IPNetwork doesn't exist in the current context, at line 520

  ```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702 /fullpaths /nostdlib+ /platform:AnyCPU /errorreport:prompt /warn:4 /define:TRACE /main:EyeWitness.Program /highentropyva+ /reference:D:\a\1\s\CS\packages\CommandLineParser.2.7.82\lib\net45\CommandLine.dll /reference:D:\a\1\s\CS\packages\Costura.Fody.4.1.0\lib\net40\Costura.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" /reference:D:\a\1\s\CS\packages\Newtonsoft.Json.12.0.3\lib\net45\Newtonsoft.Json.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Activities.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.ComponentModel.DataAnnotations.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Drawing.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.IO.Compression.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.IO.Compression.FileSystem.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Net.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Windows.Forms.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.Linq.dll" /debug:pdbonly /filealign:512 /optimize+ /out:obj\Release\EyeWitness.exe /subsystemversion:6.00 /target:exe /utf8output /deterministic+ /langversion:7.3 Journalist.cs Program.cs Properties\AssemblyInfo.cs WebsiteSnapshot.cs WitnessedServer.cs "obj\Release\.NETFramework,Version=v4.5.AssemblyAttributes.cs"
##[warning]CS\EyeWitness\Program.cs(192,35): Warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
D:\a\1\s\CS\EyeWitness\Program.cs(192,35): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [D:\a\1\s\CS\EyeWitness\EyeWitness.csproj]
##[error]CS\EyeWitness\Program.cs(520,34): Error CS0103: The name 'IPNetwork' does not exist in the current context
D:\a\1\s\CS\EyeWitness\Program.cs(520,34): error CS0103: The name 'IPNetwork' does not exist in the current context [D:\a\1\s\CS\EyeWitness\EyeWitness.csproj]
##[warning]CS\EyeWitness\WitnessedServer.cs(23,23): Warning CS0414: The field 'WitnessedServer.errorState' is assigned but its value is never used
D:\a\1\s\CS\EyeWitness\WitnessedServer.cs(23,23): warning CS0414: The field 'WitnessedServer.errorState' is assigned but its value is never used [D:\a\1\s\CS\EyeWitness\EyeWitness.csproj]
  CompilerServer: server - server processed compilation - adc45da2-ce71-4682-bebe-21adf60b02a5
```

**Pull request merged**
