### PR TITLE
Fix missing dockerfile syntax

### PR DESCRIPTION
**Pull request by nicolasjulian**
Hi,
Yesterday i try to setup eyewitness with Dockerfile but unfortunately fail.
So I'm just make litle bit change in Dockerfile and everything run pretty fine.

And i want to share my change, maybe it can help others.
Thank you

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Just want to see if @netanelravid can confirm this works for him?

**Comment by netanelravid** [comment]
I'll check and update (on vacation, should be near my laptop in 24h more or less)

**Comment by ChrisTruncer** [comment]
Sounds good @netanelravid, try to relax :) and thanks for your help! If you say it looks good, I'll merge it

**Comment by netanelravid** [comment]
Just checked it, looks great, you can merge it.
I'm adding a change to the `docker build` command in the Readme.md file.

**Pull request merged**
