### PR TITLE
[Dockerfile] Default value for user ARG

### PR DESCRIPTION
**Pull request by melardev**
Set default value for user ARG in the Dockerfile. I set the value to eyewitness

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Looks good to me. Before I merge, @netanelravid do you have any objections to this?

**Comment by ChrisTruncer** [comment]
Wanted to check in one more time @netanelravid before I merged

**Comment by netanelravid** [comment]
Looks good to me.
Can be merged.

**Comment by ChrisTruncer** [comment]
Sounds great, merging this in.

Thanks everyone!

**Pull request merged**
